### ISSUE TITLE
Compilation failure on non-x86 architectures

### ISSUE THREAD

**Issue by yboettcher** [stillwater-sc/universal#323]
As it is now, I can not compile universal (or rather anything using universal) on a Raspberry Pi 4 (aarch64-linux).
This is because the static assertions in https://github.com/stillwater-sc/universal/blob/2a89a3950838d1a5508741a120003789812e77ef/include/universal/native/nonconstexpr/clang_long_double.hpp#L191  https://github.com/stillwater-sc/universal/blob/2a89a3950838d1a5508741a120003789812e77ef/include/universal/native/nonconstexpr/gcc_long_double.hpp#L197 fail (on the Raspberry Pi, `std::numeric_limits<long double>::digits` evaluates to 113).
As far as I know, x86 CPUs are the only platform (nowadays) to satisfy this requirement, making the use of an x86 machine a necessary requirement for using universal. (I also tried cross-compiling for riscv64-linux and was met with the same (and I think some more) errors).
Ideally, support for these other long double implementations would be added, or a list of supported architectures would be added to the Readme.

**Comment by theo-lemurian** [comment]
Ok, that is indeed a requirement we need to relax. We definitely want to try to support Raspberry Pi. 

To confirm, on the ARM processor on a Raspberry Pi, the long double is a proper 128b quad precision floating-point?

**Comment by yboettcher** [comment]
> To confirm, on the ARM processor on a Raspberry Pi, the long double is a proper 128b quad precision floating-point?

I assume that's true, yes.
Using a simple test program
```cxx
#include <iostream>
#include <limits>

int main() {
  using Scalar = long double;
  
  std::cout << std::numeric_limits<Scalar>::max_exponent << std::endl;
  std::cout << std::numeric_limits<Scalar>::min_exponent << std::endl;
  std::cout << std::numeric_limits<Scalar>::digits << std::endl;
}
```
I get values consistent with a standard 128b IEEE float:
```
16384
-16381
113
```
The exponent range of about 32000 suggests 15 exponent bits. With the sign bit, this leaves 112 bits for the mantissa, which aligns with https://en.wikipedia.org/wiki/Quadruple-precision_floating-point_format. In an attempt to find a more credible source than "looks like IEEE", I looked through some LLVM documentation, and it seems like it only mentions two possible 128 bit floating point formats: one specific to PowerPC architectures and the IEEE 128 bit format.
See https://github.com/llvm/llvm-project/blob/main/llvm/docs/LangRef.rst, which describes the LLVM language (through which all clang compiled code has to go):
> Hexadecimal format is always used for long double, and
> there are three forms of long double. The 80-bit format used by x86 is
> represented as ``0xK`` followed by 20 hexadecimal digits. The 128-bit format
> used by PowerPC (two adjacent doubles) is represented by ``0xM`` followed by 32
> hexadecimal digits. The IEEE 128-bit format is represented by ``0xL`` followed
> by 32 hexadecimal digits. Long doubles will only work if they match the long
> double format on your target.

**Comment by theo-lemurian** [comment]
@yboettcher I have a new build 33a8aa0 for branch v3.68 that has the static_assert removed. The functionality is missing as I do not know what the frexp() support is for these compilers. I will need to set up a test environment. What is your set up for the Raspberry Pi?

**Comment by Ravenwater** [comment]
@yboettcher Tag v3.69 now builds on Apple ARM M1 silicon. I do not have an Arduino set up so I need some help to see if this release supports Arduino. The ARM environment creates a new combination set for compilers and architectures. The MacOS environment is a Clang and ARM64 environment and the v3.69 release supports that combination. But since this is implemented with compilation guards, it is brittle.

Love to hear if this works verbatim on the Arduino platform. Please let me know.

**Comment by yboettcher** [comment]
I am still getting a compilation error (albeit a different one) on the Raspberry Pi with v3.69 and clang15:
```
[  4%] Building CXX object tools/cmd/CMakeFiles/float2posit.dir/float2posit.cpp.o
In file included from /mnt/RamDisk/universal/tools/cmd/float2posit.cpp:6:
In file included from /mnt/RamDisk/universal/./include/universal/number/posit/posit.hpp:63:
In file included from /mnt/RamDisk/universal/./include/universal/number/posit/posit_impl.hpp:40:
/mnt/RamDisk/universal/./include/universal/internal/value/value.hpp:282:5: error: no matching function for call to 'extract_fp_components'
                                extract_fp_components(rhs, _sign, _exponent, _fr, _63b_fraction_without_hidden_bit);
                                ^~~~~~~~~~~~~~~~~~~~~
/mnt/RamDisk/universal/./include/universal/native/nonconstexpr/extract_fp_components.hpp:32:13: note: candidate function not viable: no known conversion from 'unsigned long long' to 'std::uint64_t &' (aka 'unsigned long &') for 5th argument
inline void extract_fp_components(long double fp, bool& _sign, int& _exponent, long double& _fr, std::uint64_t& _fraction) {
            ^
/mnt/RamDisk/universal/./include/universal/native/nonconstexpr/extract_fp_components.hpp:23:13: note: candidate function not viable: no known conversion from 'long double' to 'double &' for 4th argument
inline void extract_fp_components(double fp, bool& _sign, int& _exponent, double& _fr, unsigned long long& _fraction) {
            ^
/mnt/RamDisk/universal/./include/universal/native/nonconstexpr/extract_fp_components.hpp:16:13: note: candidate function not viable: no known conversion from 'long double' to 'float &' for 4th argument
inline void extract_fp_components(float fp, bool& _sign, int& _exponent, float& _fr, unsigned int& _fraction) {
            ^
1 error generated.
make[2]: *** [tools/cmd/CMakeFiles/float2posit.dir/build.make:76: tools/cmd/CMakeFiles/float2posit.dir/float2posit.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1150: tools/cmd/CMakeFiles/float2posit.dir/all] Error 2
make: *** [Makefile:146: all] Error 2
```
Which is weird because it cannot convert `unsigned long long` into `unsigned long`, although they both seem to be 8 bytes in size. This
```cpp
#include <iostream>

int main() {

  std::cout << sizeof(unsigned long long) << std::endl;
  std::cout << sizeof(unsigned long) << std::endl;
}
```
produces
```
8
8
```
on my pi.

This is a little confusing to me though. I first assumed that the `unsigned long long` was 16 bytes in size (and converting into 8 bytes wasn't possible). This would then look like a new version of the [extract_fp_components](https://github.com/stillwater-sc/universal/blob/main/include/universal/native/nonconstexpr/extract_fp_components.hpp) function was needed, which takes a 128 bit integer as its very last argument. But apparently, the `unsigned long long` is just 8 bytes...
However, to fit the mantissa of a quad-precision IEEE, I think a version taking a 128 bit type is still required.

In any case, I was wondering why it works on the Apple M1 and found this: https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Handle-data-types-and-data-alignment-properly, which states that "The long double type is a double precision IEEE754 binary floating-point type, which makes it **identical to the double** type." So working on the Apple M1 is apparently unrelated to quad-precision floating numbers.

**Comment by yboettcher** [comment]
To me, the strangest part of all this is the way the sizes of various types vary from platform to platform. E.g. for the Pi, the `long double` is twice as large as the `double`, but the `long long` is just as large as a `long`.

I found the `LDBL_MANT_DIG` value from `<float.h>` which would allow to compile a different version of the extract_fp_components based on the available mantissa bits (and thus exchanging the final parameter for one that can hold the mantissa, e.g. __uint128_t).
However, I guess there are multiple occasions across universal that assumed the mantissa to fit within a 64 bit type, which would no longer be a valid assumption then.
Also, it seems like 128 bit integers are an implementation thing and not required by the C++ standard, in which case we would have to hope for whatever compiler is used with quad-precision floating numbers to also support 128 bit integers.

I'll try to get something working on the Pi, but I can't promise anything.

**Comment by theo-lemurian** [comment]
for extract_fp_components to support a true 128-bit long double while still having a common signature would require that we provide two uint64_t's for the fraction bits to receive the upper and the lower set of a full 128-bit quad precision long double.

The forward-looking way is to move to the C++20 <bit> library, which should hide all this gnarliness. 

The only place where the floating-point field extractions are used is in the operator=() method of the Universal types when assigning a native floating-point. That conversion requires the interpretation of the exponent and fraction bits. Within Universal, there is an adaptive triple that unifies this so so that we can do this conversion in one place and then have a standard method for any of the types. But the pattern hasn't been fully developed yet as I am still trying to figure out how to leverage the bisection interpretation of number system design from LLNL. 

Recap: to support a true 128-bit quad precision long double, we would need to solve the conversion problem for each type being assigned such a value. This gets into the bowels of the library as the correct code will need to be presented to the compiler for the underlying architecture to work.

Not rocket science, but not trivial either.

**Comment by yboettcher** [comment]
I now have something that compiles, I added some asserts and am now compiling again and check whether ctest still works.
When all is fine, I'll open a draft PR.

Actually, universal already had a 128 bit integer type consisting of two uint64s, defined in the bitblock.hpp as well as a extract_long_double_fraction that works with this type. So (until now) it was mostly a matter of actually making use of them.

**Comment by theo-lemurian** [comment]
Excellent. 

One of the design rules in the library is that each type needs to stand-alone so that each can be used efficiently in isolation.  That is to say that it would be a mistake to use the integer<> type to function as a container for this section of the library, which deals with floating-point field interpretation. 

As I indicated, a better solution is to go to a new signature with two uint64_ts to hold an upper and a lower segment of a 112bit fraction.

Currently, the only hardware that I know that supports quad precision is the IBM POWER architecture. I do not have access to such a system. The RISC-V spec has also a 128bit quad precision floating-point but none of the software stacks support it, and IMHO they are unlikely because they need to compete with the ARM software stack and supporting a 128bit long double will blow up the math libraries in size and make the software stack uncompetitive against ARM.

**Comment by yboettcher** [comment]
About the stand-aloneness of the uint128 in https://github.com/stillwater-sc/universal/pull/336. It is defined inside the bitblock.hpp file which is already included by value.hpp because it supplies the `extract_52b_fraction<fbits>(...)` functions, so no new dependencies should have been created. I think the only thing I added in that regard is including the bitblock in the extract_fp_components file, because we need access to the uint128 (but I guess the value.hpp would have included this anyways. I'm just including it earlier now.). Additionally, since the uint128 is an internal type, this does not create any interdependencies between the types universal offers to users.

> a better solution is to go to a new signature with two uint64_ts

Actually that's exactly how it is defined in bitblock.hpp: https://github.com/stillwater-sc/universal/blob/e5e8449ad580b69baa52a96dcf68c986c9bb2e5f/include/universal/internal/bitblock/bitblock.hpp#L296-L299

As for the hardware support, are you referring to true hardware support? Because it seems that, while the Raspberry Pi does use a 128 bit long double, these are software implementations (If I read https://developer.arm.com/documentation/ka004751/1-0 right).

**Comment by Ravenwater** [comment]
My comment was to take that uint128 struct out of bitblock and appropriate it as a reusable 128bit container and expand its use cases.

**Comment by Ravenwater** [comment]
@yboettcher FYI I won't touch that part of the library till your PR is merged and we have a clear picture of how the 128-bit long double presents itself.

**Comment by Ravenwater** [comment]
PR has been merged, and we now have working builds for Raspberry Pi and Apple M1
