### ISSUE TITLE
exp function flushing to zero

### ISSUE THREAD

**Issue by cjdelisle** [stillwater-sc/universal#99]
I started running universal tests against the posit library which I'm working on and I found a disagreement with the `exp()` function. It seems that exp flushes to zero for large negative inputs rather than giving minpos.
https://github.com/stillwater-sc/universal/blob/master/c_api/test/posit/posit16.c#L183

**Comment by Ravenwater** [comment]
That make sense as we do not yet have a native posit implementation of exp, so we are using the C++ math library's version and marshal to and from double. Since the IEEE version will round to 0, the subsequent conversion will yield a posit<nbits,es> 0 as well.

Two options:
1- kludge it together with a special case catching the minpos rounding situation
2- implement a native posit exp function. 

We have an algorithm for nbits = 16. Still doing research on how this would need to be parameterized for arbitrary posit configurations.

**Comment by cjdelisle** [comment]
For myself, I updated the test by adding:

```
if (dref == 0.0) { pref = posit16_MIN; }
```

I think whether the library uses double/float or a multi precision library (I'm using mpfr) there is always some specialization needed in order to make the results adhere to the posit rules.

**Comment by Ravenwater** [comment]
Agreed, this is a bug as we are not adhering to the posit rounding rules. If you would be so kind, please file a bug so we have a record of it.

**Comment by cjdelisle** [comment]
Oh, I thought this was the right place to file the bug. Where would you like me to write it up ?

**Comment by Ravenwater** [comment]
you are right again, confused with an other project that records bugs in JIRA.

I just checked in the bug fix for exp() and exp2(). Just in the master branch. Will push it into c_api branch shortly.
